---
- name: copy key files and change permissions
  hosts: manager
  gather_facts: false
  tasks:
    - name: copy keys
      copy:
        src: /vagrant/.vagrant/machines/{{ item }}/virtualbox/private_key
        dest: /home/vagrant/{{ item }}_private_key
        mode: 0400
        owner: vagrant
      with_items:
        - node1

- name: kube-masters config
  hosts: kube-masters
  gather_facts: true
  become: true
  roles:
    - kube-master
  tags:
    - kube-master

- name: kube-nodes config
  hosts: kube-nodes
  gather_facts: true
  become: true
  roles:
    - kube-node
  tags:
    - kube-node
    