---
- name: copy key files and change permissions
  hosts: localhost
  gather_facts: false
  tasks:
    - name: private key dir
      file:
        path: ~/tmp/vagrant/keys
        state: directory

    - name: copy keys
      copy:
        src: ./.vagrant/machines/{{ item }}/virtualbox/private_key
        dest: ~/tmp/vagrant/keys/{{ item }}_private_key
        mode: 0400
      with_items:
        - master-1
        - node-1
        - node-2

# should always be localhost so that keys can later be distributed out to clusert nodes from ansible server
- name: kube-cert authority
  hosts: localhost
  gather_facts: false
  become: true
  roles:
    - kube-cert
  tags:
    - kube-cert

- name: kube-docker config
  hosts: kube-docker
  gather_facts: false
  become: true
  roles:
    - kube-docker
  tags:
    - kube-docker

- name: kube-masters config
  hosts: kube-masters
  gather_facts: false
  become: true
  roles:
    - kube-master
  tags:
    - kube-master

- name: kube-nodes config
  hosts: kube-nodes
  gather_facts: false
  become: true
  roles:
    - kube-node
  tags:
    - kube-node

- name: kube-es config
  hosts: kube-es
  gather_facts: false
  become: true
  roles:
    - kube-es
  tags: 
    - kube-es
