---
kind: Service
apiVersion: v1
metadata:
  name: nginx-ds
spec:
  selector:
    app: nginx-ds
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      hostNetwork: true
      containers:
      - name: nginx-ds
        image: nginx:alpine
        ports:
        - containerPort: 80
          hostPort: 80
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        hostPath:
          path: /data