---
- name: docker restart
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    
- name: kubelet restart
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes