---
- name: .docker dir
  file:
    path: /var/lib/kubelet/.docker
    state: directory

- name: docker login
  shell: docker login {{ kube_docker_registry }} -u anonymous -p anonymous

- name: copy config.json cached credentials file
  copy:
    src: ~/.docker/config.json
    dest: /var/lib/kubelet/.docker/config.json
    remote_src: true