---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deploy
  namespace: jenkins
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-deploy
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["ingresses"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-deploy
subjects:
- kind: ServiceAccount
  name: jenkins-deploy
  namespace: jenkins
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: jenkins-deploy
  apiGroup: ""
