---
- name: kubelet restart
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: kube-proxy restart
  systemd:
    name: kube-proxy
    state: restarted
    daemon_reload: yes

- name: kube sysctl reload
  command: /sbin/sysctl -p {{ kube_sysctl_file }}
